[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_first_party = "neighborly"
src_paths = ["src/neighborly", "test", "samples"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
